release:
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - freebsd
    - windows
    - darwin
    - linux
    - dragonfly
    - netbsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goarm:
    - 6
    - 7
  ldflags:
    - -s -w -X main.githash={{.ShortCommit}}

archives:
  -
    id: matterbridge
    builds:
    - matterbridge
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    files:
      - none*
    replacements:
      386: 32bit
      amd64: 64bit

checksum:
  name_template: 'checksums.txt'
