language: go
go_import_path: github.com/42wim/matterbridge

# We have everything vendored so this helps TravisCI not run `go get ...`.
install: true

git:
  depth: 200

notifications:
  email: false

branches:
  only:
  - master
  - /.*/

jobs:
  include:
  - stage: lint
    # Run linting in one Go environment only.
    script: ./ci/lint.sh
    go: 1.12.x
    env:
    - GO111MODULE=on
    - GOLANGCI_VERSION="v1.17.1"
  - stage: test
    # Run tests in a combination of Go environments.
    script: ./ci/test.sh
    go: 1.11.x
    env:
    - GO111MODULE=off
  - script: ./ci/test.sh
    go: 1.11.x
    env:
    - GO111MODULE=on
  - script: ./ci/test.sh
    go: 1.12.x
    env:
    - GO111MODULE=on
    - REPORT_COVERAGE=1
    - BINDEPLOY=1

before_deploy: /bin/bash ci/bintray.sh

deploy:
  on:
    all_branches: true
    condition: $BINDEPLOY = 1
  provider: bintray
  edge:
    branch: v1.8.47
  file: ci/deploy.json
  user: 42wim
  key:
    secure: "CeXXe6JOmt7HYR81MdWLua0ltQHhDdkIeRGBFbgd7hkb1wi8eF9DgpAcQrTso8NIlHNZmSAP46uhFgsRvkuezzX0ygalZ7DCJyAyn3sAMEh+UQSHV1WGThRehTtidqRGjetzsIGSwdrJOWil+XTfbO1Z8DGzfakhSuAZka8CM4BAoe3YeP9rYK8h+84x0GHfczvsLtXZ3mWLvQuwe4pK6+ItBCUg0ae7O7ZUpWHy0xQQkkWztY/6RAzXfaG7DuGjIw+20fhx3WOXRNpHCtZ6Bc3qERCpk0s1HhlQWlrN9wDaFTBWYwlvSnNgvxxMbNXJ6RrRJ0l0bA7FUswYwyroxhzrGLdzWDg8dHaQkypocngdalfhpsnoO9j3ApJhomUFJ3UoEq5nOGRUrKn8MPi+dP0zE4kNQ3e4VNa1ufNrvfpWolMg3xh8OXuhQdD5wIM5zFAbRJLqWSCVAjPq4DDPecmvXBOlIial7oa312lN5qnBnUjvAcxszZ+FUyDHT1Grxzna4tMwxY9obPzZUzm7359AOCCwIQFVB8GLqD2nwIstcXS0zGRz+fhviPipHuBa02q5bGUZwmkvrSNab0s8Jo7pCrel2Rz3nWPKaiCfq2WjbW1CLheSMkOQrjsdUd1hhbqNWFPUjJPInTc77NAKCfm5runv5uyowRLh4NNd0sI="
